### ISSUE TITLE
Future of Arcus.WebApi.Security

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#143]
A while back we've deprecated `Arcus.WebApi.Security` in favor of `Arcus.WebApi.Security.Authentication` and recently have introduced `Arcus.WebApi.Security.Authorization`.

So there are a few approaches:
1. We remove `Arcus.WebApi.Security` and you have to pull in `Arcus.WebApi.Security.Authentication` & `Arcus.WebApi.Security.Authorization` seperately
1. We keep `Arcus.WebApi.Security` as metapackage which pulls in `Arcus.WebApi.Security.Authentication` & `Arcus.WebApi.Security.Authorization` for you, but SAS auth which is obsolete under `Arcus.WebApi.Security` package will be gone
1. Move everything back to `Arcus.WebApi.Security` for sake of simplicity, but no way to pull in only one or the other.

**Comment by tomkerkhove** [comment]
Adding @MassimoC @wseye @mbraekman @fgheysels @SamVanhoutte @gverstraete

**Comment by fgheysels** [comment]
I would be in favor of option nr 3.

Why: 
- IMO, you can only have authorization if you have authentication
- If you require authentication, you'll most likely also need authorization
- For simplicity, it would be better to have one single package instead of having to pull in multiple packages for functionality that is so closely related.

/my 2 cents.

**Comment by SamVanhoutte** [comment]
agreeing with @fgheysels , it's definitely not handy to pull two different packages.  
so I'd vote against option 1 and leave the other options open for what works best from a software point of view, as it doesn't really impact the user of Arcus, as far as I see ?

**Comment by tomkerkhove** [comment]
So we'll merge things then! Should be done fairly soon via #144
