### ISSUE TITLE
Provide integration with IConfigurationBuilder.AddAzureKeyVault

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#53]
[IConfigurationBuilder.AddAzureKeyVault](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azurekeyvaultconfigurationextensions.addazurekeyvault?view=aspnetcore-2.2#Microsoft_Extensions_Configuration_AzureKeyVaultConfigurationExtensions_AddAzureKeyVault_Microsoft_Extensions_Configuration_IConfigurationBuilder_System_String_Microsoft_Extensions_Configuration_AzureKeyVault_IKeyVaultSecretManager_) allows you to pass an `IKeyVaultSecretManager` which extends the default working.

Maybe it's interesting to provide the same capabilities as our client via `IKeyVaultSecretManager` so that we can benefit from the caching capabilities that we provide.

*Edit: This is why we'll provide an alternative to the current approach in .NET Core 2.2 ([blog post](https://blog.tomkerkhove.be/2019/07/29/the-danger-of-using-config-addazurekeyvault-in-net-core/))*

**Comment by stijnmoreels** [comment]
## Problem
After researching the `IKeyVaultSecretManager` interface contract, it came to my attention that the implementation only consist of two methods:
* `bool Load(...)` which determines if an (already) retrieved key vault secret should be used in the token replacement, and
* `string GetKey(...)` which allows a custom mapping for the (already) retrieved key vault secret.

This is by no means the functionality we were trying to implement since we would like to control the actual **retrieval** of the key vault secrets.

## Proposal
A solution could be to implement the `ConfigurationProvider` that takes in an `ISecretProvider`. There would have to be another extension method (`.AddKeyVault`) that would allow us to manipulate the configuration builder.

**Comment by tomkerkhove** [comment]
Given you will be able to [configure the reload as of .NET Core 3.0](https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.AzureKeyVault/src/AzureKeyVaultConfigurationExtensions.cs#L153) ([PR](https://github.com/aspnet/Extensions/pull/1054)) I think it's best to close this issue.

We could implement this for .NET Core 2.x but I think it's better to recommend using our provider directly.

**Comment by tomkerkhove** [comment]
Oh well why not, let's do a quick POC to see how much effort it would take @stijnmoreels?

Like your suggestion and should be fairly easy, no?

**Comment by stijnmoreels** [comment]
Yes, I already had some parts already written.
It would need though, a list of key names for which you would want to retrieve the secret value, since the way the `ConfigurationProvider` works.

If you look for example to the implemented configuration provider for environment variables, they also retrieve ALL variables.

**Comment by tomkerkhove** [comment]
> It would need though, a list of key names for which you would want to retrieve the secret value, since the way the ConfigurationProvider works.

What do you mean here? Can you point to where you've found this please?

> If you look for example to the implemented configuration provider for environment variables, they also retrieve ALL variables on your machine.

As far as I'm concerned we should just give them the secret they are requesting and not whitelist names so I think that's what they do here or do you mean to get all the secrets at once?

**Comment by stijnmoreels** [comment]
> > It would need though, a list of key names for which you would want to retrieve the secret value, since the way the ConfigurationProvider works.
> 
> What do you mean here? Can you point to where you've found this please?
> 
Look for example to [this line](https://github.com/aspnet/Extensions/blob/2116b161b2957bba7b3f09f5f334687c9effccd1/src/Configuration/Config.EnvironmentVariables/src/EnvironmentVariablesConfigurationProvider.cs#L46) where the environment variables are being used to switch tokens with values.
In the key vault impelemtation, they also retrieve the entire set of secrets that are available in the vavult. This complete set is then set as data which further is used to switch tokens/values.

We don't have that kind of functionality in our `ISecretProvider`  implementation. Only `string Get(secretKey)`. Which means we need some kind of list that describes WHAT secrets we need to retrieve.

**Comment by tomkerkhove** [comment]
Frankly, if there is one thing I do *not* want to support is getting a list of all secrets.

We can also just override [`TryGet`](https://github.com/aspnet/Extensions/blob/2116b161b2957bba7b3f09f5f334687c9effccd1/src/Configuration/Config/src/ConfigurationProvider.cs#L38) and run our logic there
